import type { Campaign } from './types';

export const SEED_CAMPAIGNS: Campaign[] = [
  {
    id: 'cmp-festival',
    name: 'New Model Festival',
    published: true,
    startAt: '2026-08-01T00:00',
    endAt: '2026-09-30T23:59',
    type: 'bonus_credits',
    rule: { kind: 'bonus_credits', percent: 35, plans: ['starter', 'pro', 'ultra'], includeTopup: true },
    popup: {
      enabled: true,
      badgeLeft: 'LIMITED TIME',
      badgeRight: 'NEW MODEL FESTIVAL',
      headlineNumber: '35%',
      headlineText: 'Extra credits',
      highlights: [
        { name: 'Seedream 5.0 Pro', status: 'LIVE NOW', icon: 'image' },
        { name: 'Seedance 2.5', status: 'COMING SOON', icon: 'video' },
      ],
      ctaText: 'Get bonus credits',
      ctaHref: '/prototypes/promo-campaigns/pricing',
    },
    pricingBanner: {
      enabled: true,
      text: 'New Model Festival — get 35% extra credits on every paid plan.',
      showCountdown: true,
    },
    frequency: { maxPerUser: 1, intervalDays: 7 },
  },
  {
    id: 'cmp-annual',
    name: 'Annual Plan 30% OFF',
    published: true,
    startAt: '2026-11-20T00:00',
    endAt: '2026-12-05T23:59',
    type: 'discount',
    rule: { kind: 'discount', percent: 30, plans: ['starter', 'pro', 'ultra'], billing: 'yearly' },
    popup: {
      enabled: true,
      badgeLeft: 'LIMITED TIME',
      badgeRight: 'BLACK FRIDAY',
      headlineNumber: '30%',
      headlineText: 'Off annual plans',
      highlights: [
        { name: 'All paid plans', status: 'LIVE NOW', icon: 'image' },
        { name: 'Annual billing only', status: 'LIVE NOW', icon: 'video' },
      ],
      ctaText: 'Claim discount',
      ctaHref: '/prototypes/promo-campaigns/pricing',
    },
    pricingBanner: { enabled: true, text: 'Black Friday — 30% off all annual plans.', showCountdown: true },
    frequency: { maxPerUser: 2, intervalDays: 3 },
  },
  {
    id: 'cmp-unlock',
    name: 'Seedance 2.5 Festival Unlock',
    published: true,
    startAt: '2026-08-05T00:00',
    endAt: '2026-09-15T23:59',
    type: 'unlock',
    rule: { kind: 'unlock', models: ['Seedance 2.0'], forPlans: ['free', 'starter'] },
    popup: {
      enabled: false,
      badgeLeft: 'LIMITED TIME',
      badgeRight: 'FESTIVAL UNLOCK',
      headlineNumber: 'NEW',
      headlineText: 'Model unlocked',
      highlights: [{ name: 'Seedance 2.0', status: 'LIVE NOW', icon: 'video' }],
      ctaText: 'Try it now',
      ctaHref: '/prototypes/promo-campaigns/pricing',
    },
    pricingBanner: {
      enabled: true,
      text: 'Festival unlock — Seedance 2.0 is open to Free and Starter until Sep 15.',
      showCountdown: false,
    },
    frequency: { maxPerUser: 1, intervalDays: 7 },
  },
  {
    id: 'cmp-spring',
    name: 'Spring Code SPRING50',
    published: true,
    startAt: '2026-03-01T00:00',
    endAt: '2026-03-31T23:59',
    type: 'promo_code',
    rule: { kind: 'promo_code', code: 'SPRING50', percent: 50, totalQuota: 500, perUserLimit: 1 },
    popup: {
      enabled: false,
      badgeLeft: 'LIMITED TIME',
      badgeRight: 'SPRING SALE',
      headlineNumber: '50%',
      headlineText: 'Off with code',
      highlights: [{ name: 'SPRING50', status: 'LIVE NOW', icon: 'image' }],
      ctaText: 'Redeem now',
      ctaHref: '/prototypes/promo-campaigns/pricing',
    },
    pricingBanner: { enabled: false, text: '', showCountdown: false },
    frequency: { maxPerUser: 1, intervalDays: 7 },
  },
];
