import type { Campaign, RedeemCode } from './types';

export const SEED_CAMPAIGNS: Campaign[] = [
  {
    id: 'cmp-festival',
    name: 'New Model Festival',
    published: true,
    startAt: '2026-08-01T00:00',
    endAt: '2026-09-30T23:59',
    type: 'bonus_credits',
    rule: { kind: 'bonus_credits', percent: 35, plans: ['starter', 'pro', 'ultra'], includeTopup: true },
    popup: {
      enabled: true,
      badgeLeft: 'LIMITED TIME',
      badgeRight: 'NEW MODEL FESTIVAL',
      headlineNumber: '35%',
      headlineText: 'Extra credits',
      highlights: [
        { name: 'Seedream 5.0 Pro', status: 'LIVE NOW', icon: 'image' },
        { name: 'Seedance 2.5', status: 'COMING SOON', icon: 'video' },
      ],
      ctaText: 'Get bonus credits',
      ctaHref: '/prototypes/promo-campaigns/pricing',
    },
    pricingBanner: {
      enabled: true,
      text: 'New Model Festival — get 35% extra credits on every paid plan.',
      showCountdown: true,
    },
    frequency: { maxPerUser: 1, intervalDays: 7 },
  },
  {
    id: 'cmp-annual',
    name: 'Annual Plan 30% OFF',
    published: true,
    startAt: '2026-11-20T00:00',
    endAt: '2026-12-05T23:59',
    type: 'discount',
    rule: { kind: 'discount', percent: 30, plans: ['starter', 'pro', 'ultra'], billing: 'yearly' },
    popup: {
      enabled: true,
      badgeLeft: 'LIMITED TIME',
      badgeRight: 'BLACK FRIDAY',
      headlineNumber: '30%',
      headlineText: 'Off annual plans',
      highlights: [
        { name: 'All paid plans', status: 'LIVE NOW', icon: 'image' },
        { name: 'Annual billing only', status: 'LIVE NOW', icon: 'video' },
      ],
      ctaText: 'Claim discount',
      ctaHref: '/prototypes/promo-campaigns/pricing',
    },
    pricingBanner: { enabled: true, text: 'Black Friday — 30% off all annual plans.', showCountdown: true },
    frequency: { maxPerUser: 2, intervalDays: 3 },
  },
  {
    id: 'cmp-unlock',
    name: 'Seedance 2.5 Festival Unlock',
    published: true,
    startAt: '2026-08-05T00:00',
    endAt: '2026-09-15T23:59',
    type: 'unlock',
    rule: { kind: 'unlock', models: ['Seedance 2.0'], forPlans: ['free', 'starter'] },
    popup: {
      enabled: false,
      badgeLeft: 'LIMITED TIME',
      badgeRight: 'FESTIVAL UNLOCK',
      headlineNumber: 'NEW',
      headlineText: 'Model unlocked',
      highlights: [{ name: 'Seedance 2.0', status: 'LIVE NOW', icon: 'video' }],
      ctaText: 'Try it now',
      ctaHref: '/prototypes/promo-campaigns/pricing',
    },
    pricingBanner: {
      enabled: true,
      text: 'Festival unlock — Seedance 2.0 is open to Free and Starter until Sep 15.',
      showCountdown: false,
    },
    frequency: { maxPerUser: 1, intervalDays: 7 },
  },
  {
    id: 'cmp-newuser',
    name: 'New User Welcome',
    published: true,
    startAt: '2026-01-01T00:00',
    endAt: '2026-12-31T23:59',
    type: 'promo_code',
    rule: { kind: 'promo_code', code: 'WELCOME30', percent: 30, totalQuota: 0, perUserLimit: 1 },
    codeId: 'code-welcome',
    art: 'newuser',
    popup: {
      enabled: true,
      badgeLeft: 'FIRST ORDER',
      badgeRight: 'WELCOME',
      headlineNumber: '30%',
      headlineText: 'Off your first plan',
      highlights: [{ name: 'Any paid plan', status: 'LIVE NOW', icon: 'image' }],
      ctaText: 'Claim 30% off',
      ctaHref: '/prototypes/promo-campaigns/pricing',
    },
    pricingBanner: {
      enabled: true,
      text: 'New here? 30% off your first plan — applied automatically at checkout.',
      showCountdown: false,
    },
    frequency: { maxPerUser: 1, intervalDays: 30 },
  },
  {
    id: 'cmp-halloween',
    name: 'Halloween Sale',
    published: true,
    startAt: '2026-10-24T00:00',
    endAt: '2026-11-02T23:59',
    type: 'promo_code',
    rule: { kind: 'promo_code', code: 'HALLOWEEN25', percent: 25, totalQuota: 500, perUserLimit: 1 },
    codeId: 'code-halloween',
    art: 'halloween',
    popup: {
      enabled: true,
      badgeLeft: 'LIMITED TIME',
      badgeRight: 'HALLOWEEN',
      headlineNumber: '25%',
      headlineText: 'Off every plan',
      highlights: [{ name: 'All paid plans', status: 'LIVE NOW', icon: 'image' }],
      ctaText: 'Grab the deal',
      ctaHref: '/prototypes/promo-campaigns/pricing',
    },
    pricingBanner: {
      enabled: true,
      text: 'Halloween Sale — 25% off every plan until Nov 2.',
      showCountdown: true,
    },
    frequency: { maxPerUser: 2, intervalDays: 2 },
  },
  {
    id: 'cmp-blackfriday',
    name: 'Black Friday',
    published: false,
    startAt: '2026-11-27T00:00',
    endAt: '2026-12-01T23:59',
    type: 'promo_code',
    rule: { kind: 'promo_code', code: 'BLACKFRIDAY50', percent: 50, totalQuota: 2000, perUserLimit: 1 },
    codeId: 'code-blackfriday',
    art: 'blackfriday',
    popup: {
      enabled: true,
      badgeLeft: 'BIGGEST SALE',
      badgeRight: 'BLACK FRIDAY',
      headlineNumber: '50%',
      headlineText: 'Off every plan',
      highlights: [{ name: 'All paid plans', status: 'COMING SOON', icon: 'image' }],
      ctaText: 'See the deal',
      ctaHref: '/prototypes/promo-campaigns/pricing',
    },
    pricingBanner: {
      enabled: true,
      text: 'Black Friday — 50% off every plan. Ends Dec 1.',
      showCountdown: true,
    },
    frequency: { maxPerUser: 3, intervalDays: 1 },
  },
];

export const SEED_CODES: RedeemCode[] = [
  {
    id: 'code-welcome',
    code: 'WELCOME30',
    note: '新用户首单优惠,常驻',
    percent: 30,
    maxRedemptions: 0,
    redeemed: 1284,
    perUserLimit: 1,
    firstTimeOnly: true,
    expiresAt: '',
    active: true,
  },
  {
    id: 'code-halloween',
    code: 'HALLOWEEN25',
    note: '万圣节折扣活动',
    percent: 25,
    maxRedemptions: 500,
    redeemed: 137,
    perUserLimit: 1,
    firstTimeOnly: false,
    expiresAt: '2026-11-02T23:59',
    active: true,
  },
  {
    id: 'code-blackfriday',
    code: 'BLACKFRIDAY50',
    note: '黑五折扣活动,活动未发布前先停用',
    percent: 50,
    maxRedemptions: 2000,
    redeemed: 0,
    perUserLimit: 1,
    firstTimeOnly: false,
    expiresAt: '2026-12-01T23:59',
    active: false,
  },
  {
    id: 'code-spring',
    code: 'SPRING50',
    note: '春季活动,已结束',
    percent: 50,
    maxRedemptions: 500,
    redeemed: 500,
    perUserLimit: 1,
    firstTimeOnly: false,
    expiresAt: '2026-03-31T23:59',
    active: false,
  },
];
